site_name: ChemNLP Documentation
theme:
  name: material
nav:
  - Home: index.md
  - User Guide:
      - Installation: user-guide/installation.md
      - Quick Start: user-guide/quickstart.md
  - API Reference:
      - Sampler Module: api/sampler.md
      - Sampler CLI: api/sampler_cli.md
      - Meta YAML Generator: api/meta_yaml_generator.md
      - Meta YAML Augmentor: api/meta_yaml_augmentor.md
  - Examples:
      - Basic Usage: examples/basic-usage.md
      - Advanced Techniques: examples/advanced-techniques.md
  - Contributing: CONTRIBUTING.md
  - Changelog: changelog.md
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
