group:
- chemnlp
- bicerano_dataset
task: _benchmark_multiple_choice
dataset_path: /Users/kevinmaikjablonka/git/openbioml/chemnlp/sampled/bicerano_dataset/chunk_0/template_5
dataset_name: _benchmark_multiple_choice
output_type: loglikelihood
doc_to_text: input
metric_list:
- metric: perplexity
  aggregation: perplexity
  higher_is_better: false
doc_to_target: output
training_split: train
validation_split: valid
test_split: test
